version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Setup DB
          command: bundle exec rake db:create && bundle exec rake db:migrate
      - run:
          name: Run tests
          command: bundle exec rails test

